FROM quay.io/jupyter/scipy-notebook:python-3.11

USER root

RUN pip install --no-cache-dir \
    kafka-python==2.0.2 \
    opentelemetry-api==1.24.0 \
    opentelemetry-sdk==1.24.0 \
    opentelemetry-exporter-otlp==1.24.0 \
    scikit-learn==1.8.0 \
    joblib==1.4.2 \
    seaborn==0.13.2

USER jovyan
WORKDIR /home/jovyan/work
